-- -------------------------------------------------------------
--
-- Module: firfilter
-- Generated by MATLAB(R) 9.11 and Filter Design HDL Coder 3.1.10.
-- Generated on: 2022-04-26 02:28:02
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- Name: firfilter
-- TestBenchName: firfilter_tb
-- TestBenchStimulus: impulse step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 25
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : s24,23 -> [-1 1)
-- Input             : s24,23 -> [-1 1)
-- Filter Internals  : Full Precision
--   Output          : s48,46 -> [-2 2)  (auto determined)
--   Product         : s46,46 -> [-5.000000e-01 5.000000e-01)  (auto determined)
--   Accumulator     : s48,46 -> [-2 2)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY firfilter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(23 DOWNTO 0); -- sfix24_En23
         filter_out                      :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En46
         );

END firfilter;


----------------------------------------------------------------
--Module Architecture: firfilter
----------------------------------------------------------------
ARCHITECTURE rtl OF firfilter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(23 DOWNTO 0); -- sfix24_En23
  -- Constants
  CONSTANT coeff1                         : signed(23 DOWNTO 0) := to_signed(-180643, 24); -- sfix24_En23
  CONSTANT coeff2                         : signed(23 DOWNTO 0) := to_signed(88561, 24); -- sfix24_En23
  CONSTANT coeff3                         : signed(23 DOWNTO 0) := to_signed(226561, 24); -- sfix24_En23
  CONSTANT coeff4                         : signed(23 DOWNTO 0) := to_signed(70356, 24); -- sfix24_En23
  CONSTANT coeff5                         : signed(23 DOWNTO 0) := to_signed(-218556, 24); -- sfix24_En23
  CONSTANT coeff6                         : signed(23 DOWNTO 0) := to_signed(-122904, 24); -- sfix24_En23
  CONSTANT coeff7                         : signed(23 DOWNTO 0) := to_signed(327391, 24); -- sfix24_En23
  CONSTANT coeff8                         : signed(23 DOWNTO 0) := to_signed(354439, 24); -- sfix24_En23
  CONSTANT coeff9                         : signed(23 DOWNTO 0) := to_signed(-359247, 24); -- sfix24_En23
  CONSTANT coeff10                        : signed(23 DOWNTO 0) := to_signed(-759243, 24); -- sfix24_En23
  CONSTANT coeff11                        : signed(23 DOWNTO 0) := to_signed(411379, 24); -- sfix24_En23
  CONSTANT coeff12                        : signed(23 DOWNTO 0) := to_signed(2632432, 24); -- sfix24_En23
  CONSTANT coeff13                        : signed(23 DOWNTO 0) := to_signed(3780533, 24); -- sfix24_En23
  CONSTANT coeff14                        : signed(23 DOWNTO 0) := to_signed(2632432, 24); -- sfix24_En23
  CONSTANT coeff15                        : signed(23 DOWNTO 0) := to_signed(411379, 24); -- sfix24_En23
  CONSTANT coeff16                        : signed(23 DOWNTO 0) := to_signed(-759243, 24); -- sfix24_En23
  CONSTANT coeff17                        : signed(23 DOWNTO 0) := to_signed(-359247, 24); -- sfix24_En23
  CONSTANT coeff18                        : signed(23 DOWNTO 0) := to_signed(354439, 24); -- sfix24_En23
  CONSTANT coeff19                        : signed(23 DOWNTO 0) := to_signed(327391, 24); -- sfix24_En23
  CONSTANT coeff20                        : signed(23 DOWNTO 0) := to_signed(-122904, 24); -- sfix24_En23
  CONSTANT coeff21                        : signed(23 DOWNTO 0) := to_signed(-218556, 24); -- sfix24_En23
  CONSTANT coeff22                        : signed(23 DOWNTO 0) := to_signed(70356, 24); -- sfix24_En23
  CONSTANT coeff23                        : signed(23 DOWNTO 0) := to_signed(226561, 24); -- sfix24_En23
  CONSTANT coeff24                        : signed(23 DOWNTO 0) := to_signed(88561, 24); -- sfix24_En23
  CONSTANT coeff25                        : signed(23 DOWNTO 0) := to_signed(-180643, 24); -- sfix24_En23

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 24); -- sfix24_En23
  SIGNAL product25                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp                         : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product24                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_1                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product23                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_2                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product22                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_3                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product21                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_4                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product20                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_5                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product19                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_6                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product18                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_7                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product17                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_8                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product16                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_9                       : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product15                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_10                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product14                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_11                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product13                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_12                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product12                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_13                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product11                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_14                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product10                        : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_15                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product9                         : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_16                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product8                         : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_17                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product7                         : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_18                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product6                         : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_19                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product5                         : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_20                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product4                         : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_21                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product3                         : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_22                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product2                         : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_23                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product1_cast                    : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL product1                         : signed(45 DOWNTO 0); -- sfix46_En46
  SIGNAL mul_temp_24                      : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL sum1                             : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp                         : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum2                             : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_1                       : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum3                             : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_2                       : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum4                             : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_3                       : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum5                             : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_4                       : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum6                             : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_5                       : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum7                             : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_6                       : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum8                             : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_7                       : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum9                             : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_8                       : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum10                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_9                       : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum11                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_10                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum12                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_11                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum13                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_12                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum14                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_13                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum15                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_14                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum16                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_15                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum17                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_16                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum18                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_17                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum19                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_18                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum20                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_19                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum21                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_20                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum22                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_21                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum23                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_22                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL sum24                            : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL add_temp_23                      : signed(48 DOWNTO 0); -- sfix49_En46
  SIGNAL output_typeconvert               : signed(47 DOWNTO 0); -- sfix48_En46
  SIGNAL output_register                  : signed(47 DOWNTO 0); -- sfix48_En46


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 24) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 24) <= delay_pipeline(0 TO 23);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(24) * coeff25;
  product25 <= mul_temp(45 DOWNTO 0);

  mul_temp_1 <= delay_pipeline(23) * coeff24;
  product24 <= mul_temp_1(45 DOWNTO 0);

  mul_temp_2 <= delay_pipeline(22) * coeff23;
  product23 <= mul_temp_2(45 DOWNTO 0);

  mul_temp_3 <= delay_pipeline(21) * coeff22;
  product22 <= mul_temp_3(45 DOWNTO 0);

  mul_temp_4 <= delay_pipeline(20) * coeff21;
  product21 <= mul_temp_4(45 DOWNTO 0);

  mul_temp_5 <= delay_pipeline(19) * coeff20;
  product20 <= mul_temp_5(45 DOWNTO 0);

  mul_temp_6 <= delay_pipeline(18) * coeff19;
  product19 <= mul_temp_6(45 DOWNTO 0);

  mul_temp_7 <= delay_pipeline(17) * coeff18;
  product18 <= mul_temp_7(45 DOWNTO 0);

  mul_temp_8 <= delay_pipeline(16) * coeff17;
  product17 <= mul_temp_8(45 DOWNTO 0);

  mul_temp_9 <= delay_pipeline(15) * coeff16;
  product16 <= mul_temp_9(45 DOWNTO 0);

  mul_temp_10 <= delay_pipeline(14) * coeff15;
  product15 <= mul_temp_10(45 DOWNTO 0);

  mul_temp_11 <= delay_pipeline(13) * coeff14;
  product14 <= mul_temp_11(45 DOWNTO 0);

  mul_temp_12 <= delay_pipeline(12) * coeff13;
  product13 <= mul_temp_12(45 DOWNTO 0);

  mul_temp_13 <= delay_pipeline(11) * coeff12;
  product12 <= mul_temp_13(45 DOWNTO 0);

  mul_temp_14 <= delay_pipeline(10) * coeff11;
  product11 <= mul_temp_14(45 DOWNTO 0);

  mul_temp_15 <= delay_pipeline(9) * coeff10;
  product10 <= mul_temp_15(45 DOWNTO 0);

  mul_temp_16 <= delay_pipeline(8) * coeff9;
  product9 <= mul_temp_16(45 DOWNTO 0);

  mul_temp_17 <= delay_pipeline(7) * coeff8;
  product8 <= mul_temp_17(45 DOWNTO 0);

  mul_temp_18 <= delay_pipeline(6) * coeff7;
  product7 <= mul_temp_18(45 DOWNTO 0);

  mul_temp_19 <= delay_pipeline(5) * coeff6;
  product6 <= mul_temp_19(45 DOWNTO 0);

  mul_temp_20 <= delay_pipeline(4) * coeff5;
  product5 <= mul_temp_20(45 DOWNTO 0);

  mul_temp_21 <= delay_pipeline(3) * coeff4;
  product4 <= mul_temp_21(45 DOWNTO 0);

  mul_temp_22 <= delay_pipeline(2) * coeff3;
  product3 <= mul_temp_22(45 DOWNTO 0);

  mul_temp_23 <= delay_pipeline(1) * coeff2;
  product2 <= mul_temp_23(45 DOWNTO 0);

  product1_cast <= resize(product1, 48);

  mul_temp_24 <= delay_pipeline(0) * coeff1;
  product1 <= mul_temp_24(45 DOWNTO 0);

  add_temp <= resize(product1_cast, 49) + resize(product2, 49);
  sum1 <= add_temp(47 DOWNTO 0);

  add_temp_1 <= resize(sum1, 49) + resize(product3, 49);
  sum2 <= add_temp_1(47 DOWNTO 0);

  add_temp_2 <= resize(sum2, 49) + resize(product4, 49);
  sum3 <= add_temp_2(47 DOWNTO 0);

  add_temp_3 <= resize(sum3, 49) + resize(product5, 49);
  sum4 <= add_temp_3(47 DOWNTO 0);

  add_temp_4 <= resize(sum4, 49) + resize(product6, 49);
  sum5 <= add_temp_4(47 DOWNTO 0);

  add_temp_5 <= resize(sum5, 49) + resize(product7, 49);
  sum6 <= add_temp_5(47 DOWNTO 0);

  add_temp_6 <= resize(sum6, 49) + resize(product8, 49);
  sum7 <= add_temp_6(47 DOWNTO 0);

  add_temp_7 <= resize(sum7, 49) + resize(product9, 49);
  sum8 <= add_temp_7(47 DOWNTO 0);

  add_temp_8 <= resize(sum8, 49) + resize(product10, 49);
  sum9 <= add_temp_8(47 DOWNTO 0);

  add_temp_9 <= resize(sum9, 49) + resize(product11, 49);
  sum10 <= add_temp_9(47 DOWNTO 0);

  add_temp_10 <= resize(sum10, 49) + resize(product12, 49);
  sum11 <= add_temp_10(47 DOWNTO 0);

  add_temp_11 <= resize(sum11, 49) + resize(product13, 49);
  sum12 <= add_temp_11(47 DOWNTO 0);

  add_temp_12 <= resize(sum12, 49) + resize(product14, 49);
  sum13 <= add_temp_12(47 DOWNTO 0);

  add_temp_13 <= resize(sum13, 49) + resize(product15, 49);
  sum14 <= add_temp_13(47 DOWNTO 0);

  add_temp_14 <= resize(sum14, 49) + resize(product16, 49);
  sum15 <= add_temp_14(47 DOWNTO 0);

  add_temp_15 <= resize(sum15, 49) + resize(product17, 49);
  sum16 <= add_temp_15(47 DOWNTO 0);

  add_temp_16 <= resize(sum16, 49) + resize(product18, 49);
  sum17 <= add_temp_16(47 DOWNTO 0);

  add_temp_17 <= resize(sum17, 49) + resize(product19, 49);
  sum18 <= add_temp_17(47 DOWNTO 0);

  add_temp_18 <= resize(sum18, 49) + resize(product20, 49);
  sum19 <= add_temp_18(47 DOWNTO 0);

  add_temp_19 <= resize(sum19, 49) + resize(product21, 49);
  sum20 <= add_temp_19(47 DOWNTO 0);

  add_temp_20 <= resize(sum20, 49) + resize(product22, 49);
  sum21 <= add_temp_20(47 DOWNTO 0);

  add_temp_21 <= resize(sum21, 49) + resize(product23, 49);
  sum22 <= add_temp_21(47 DOWNTO 0);

  add_temp_22 <= resize(sum22, 49) + resize(product24, 49);
  sum23 <= add_temp_22(47 DOWNTO 0);

  add_temp_23 <= resize(sum23, 49) + resize(product25, 49);
  sum24 <= add_temp_23(47 DOWNTO 0);

  output_typeconvert <= sum24;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
