-- -------------------------------------------------------------
--
-- Module: lowpass1
-- Generated by MATLAB(R) 9.11 and Filter Design HDL Coder 3.1.10.
-- Generated on: 2022-04-26 01:35:52
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- Name: lowpass1
-- TestBenchName: lowpass1_tb
-- TestBenchStimulus: step ramp chirp 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure    : Direct-Form II, Second-Order Sections
-- Number of Sections  : 12
-- Stable              : Yes
-- Linear Phase        : No
-- Arithmetic          : fixed
-- Numerator           : s24,23 -> [-1 1)
-- Denominator         : s24,15 -> [-256 256)
-- Scale Values        : s24,15 -> [-256 256)
-- Input               : s24,23 -> [-1 1)
-- Section Input       : s16,3 -> [-4096 4096)
-- Section Output      : s16,12 -> [-8 8)
-- Output              : s49,45 -> [-8 8)
-- State               : s16,15 -> [-1 1)
-- Numerator Prod      : s40,38 -> [-2 2)
-- Denominator Prod    : s40,30 -> [-512 512)
-- Numerator Accum     : s42,38 -> [-8 8)
-- Denominator Accum   : s42,30 -> [-2048 2048)
-- Round Mode          : convergent
-- Overflow Mode       : wrap
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY lowpass1 IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(23 DOWNTO 0); -- sfix24_En23
         filter_out                      :   OUT   std_logic_vector(48 DOWNTO 0)  -- sfix49_En45
         );

END lowpass1;


----------------------------------------------------------------
--Module Architecture: lowpass1
----------------------------------------------------------------
ARCHITECTURE rtl OF lowpass1 IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16_En15
  -- Constants
  CONSTANT scaleconst1                    : signed(23 DOWNTO 0) := to_signed(143, 24); -- sfix24_En15
  CONSTANT coeff_b1_section1              : signed(23 DOWNTO 0) := to_signed(8388607, 24); -- sfix24_En23
  CONSTANT coeff_b2_section1              : signed(23 DOWNTO 0) := to_signed(-8388608, 24); -- sfix24_En23
  CONSTANT coeff_b3_section1              : signed(23 DOWNTO 0) := to_signed(8388607, 24); -- sfix24_En23
  CONSTANT coeff_a2_section1              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section1              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section2              : signed(23 DOWNTO 0) := to_signed(8388607, 24); -- sfix24_En23
  CONSTANT coeff_b2_section2              : signed(23 DOWNTO 0) := to_signed(-3093786, 24); -- sfix24_En23
  CONSTANT coeff_b3_section2              : signed(23 DOWNTO 0) := to_signed(52192, 24); -- sfix24_En23
  CONSTANT coeff_a2_section2              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section2              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section3              : signed(23 DOWNTO 0) := to_signed(8388607, 24); -- sfix24_En23
  CONSTANT coeff_b2_section3              : signed(23 DOWNTO 0) := to_signed(-8388608, 24); -- sfix24_En23
  CONSTANT coeff_b3_section3              : signed(23 DOWNTO 0) := to_signed(8388607, 24); -- sfix24_En23
  CONSTANT coeff_a2_section3              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section3              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section4              : signed(23 DOWNTO 0) := to_signed(8388607, 24); -- sfix24_En23
  CONSTANT coeff_b2_section4              : signed(23 DOWNTO 0) := to_signed(-8388608, 24); -- sfix24_En23
  CONSTANT coeff_b3_section4              : signed(23 DOWNTO 0) := to_signed(8388607, 24); -- sfix24_En23
  CONSTANT coeff_a2_section4              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section4              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section5              : signed(23 DOWNTO 0) := to_signed(8388607, 24); -- sfix24_En23
  CONSTANT coeff_b2_section5              : signed(23 DOWNTO 0) := to_signed(-4490581, 24); -- sfix24_En23
  CONSTANT coeff_b3_section5              : signed(23 DOWNTO 0) := to_signed(1658353, 24); -- sfix24_En23
  CONSTANT coeff_a2_section5              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section5              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section6              : signed(23 DOWNTO 0) := to_signed(8388607, 24); -- sfix24_En23
  CONSTANT coeff_b2_section6              : signed(23 DOWNTO 0) := to_signed(-5630586, 24); -- sfix24_En23
  CONSTANT coeff_b3_section6              : signed(23 DOWNTO 0) := to_signed(1150487, 24); -- sfix24_En23
  CONSTANT coeff_a2_section6              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section6              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section7              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_b2_section7              : signed(23 DOWNTO 0) := to_signed(4194304, 24); -- sfix24_En23
  CONSTANT coeff_b3_section7              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_a2_section7              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section7              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section8              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_b2_section8              : signed(23 DOWNTO 0) := to_signed(4194304, 24); -- sfix24_En23
  CONSTANT coeff_b3_section8              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_a2_section8              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section8              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section9              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_b2_section9              : signed(23 DOWNTO 0) := to_signed(4194304, 24); -- sfix24_En23
  CONSTANT coeff_b3_section9              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_a2_section9              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section9              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section10             : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_b2_section10             : signed(23 DOWNTO 0) := to_signed(4194304, 24); -- sfix24_En23
  CONSTANT coeff_b3_section10             : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_a2_section10             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section10             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section11             : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_b2_section11             : signed(23 DOWNTO 0) := to_signed(4194304, 24); -- sfix24_En23
  CONSTANT coeff_b3_section11             : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_a2_section11             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section11             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_b1_section12             : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_b2_section12             : signed(23 DOWNTO 0) := to_signed(4194304, 24); -- sfix24_En23
  CONSTANT coeff_b3_section12             : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En23
  CONSTANT coeff_a2_section12             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  CONSTANT coeff_a3_section12             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En15
  -- Signals
  SIGNAL input_register                   : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL scale1                           : signed(50 DOWNTO 0); -- sfix51_En38
  SIGNAL mul_temp                         : signed(47 DOWNTO 0); -- sfix48_En38
  SIGNAL scaletypeconvert1                : signed(15 DOWNTO 0); -- sfix16_En3
  -- Section 1 Signals 
  SIGNAL a1sum1                           : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum1                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum1                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert1                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section1                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv1                       : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul1                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul1                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul1                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL unaryminus_temp                  : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL b1multypeconvert1                : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast                         : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_1                       : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp                         : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_2                       : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_3                       : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_1                       : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result1                  : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 2 Signals 
  SIGNAL a1sum2                           : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum2                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum2                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert2                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section2                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv2                       : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul2                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul2                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul2                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b1multypeconvert2                : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_4                       : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_5                       : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_2                       : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_6                       : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_7                       : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_3                       : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result2                  : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 3 Signals 
  SIGNAL a1sum3                           : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum3                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum3                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert3                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section3                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv3                       : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul3                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul3                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul3                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL unaryminus_temp_1                : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL b1multypeconvert3                : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_8                       : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_9                       : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_4                       : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_10                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_11                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_5                       : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result3                  : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 4 Signals 
  SIGNAL a1sum4                           : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum4                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum4                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert4                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section4                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv4                       : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul4                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul4                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul4                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL unaryminus_temp_2                : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL b1multypeconvert4                : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_12                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_13                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_6                       : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_14                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_15                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_7                       : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result4                  : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 5 Signals 
  SIGNAL a1sum5                           : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum5                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum5                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert5                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section5                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv5                       : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul5                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul5                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul5                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b1multypeconvert5                : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_16                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_17                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_8                       : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_18                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_19                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_9                       : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result5                  : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 6 Signals 
  SIGNAL a1sum6                           : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum6                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum6                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert6                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section6                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv6                       : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul6                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul6                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul6                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b1multypeconvert6                : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_20                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_21                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_10                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_22                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_23                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_11                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result6                  : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 7 Signals 
  SIGNAL a1sum7                           : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum7                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum7                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert7                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section7                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv7                       : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul7                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul7                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul7                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b1multypeconvert7                : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_24                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_25                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_12                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_26                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_27                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_13                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result7                  : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 8 Signals 
  SIGNAL a1sum8                           : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum8                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum8                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert8                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section8                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv8                       : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul8                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul8                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul8                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b1multypeconvert8                : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_28                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_29                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_14                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_30                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_31                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_15                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result8                  : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 9 Signals 
  SIGNAL a1sum9                           : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum9                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum9                           : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert9                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section9                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv9                       : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul9                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul9                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul9                           : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b1multypeconvert9                : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_32                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_33                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_16                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_34                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_35                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_17                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result9                  : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 10 Signals 
  SIGNAL a1sum10                          : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum10                          : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum10                          : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert10                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section10                  : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv10                      : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul10                          : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul10                          : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul10                          : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b1multypeconvert10               : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_36                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_37                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_18                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_38                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_39                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_19                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result10                 : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 11 Signals 
  SIGNAL a1sum11                          : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum11                          : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum11                          : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert11                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section11                  : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv11                      : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul11                          : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul11                          : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul11                          : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b1multypeconvert11               : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_40                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_41                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_20                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_42                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_43                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_21                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL section_result11                 : signed(41 DOWNTO 0); -- sfix42_En30
  -- Section 12 Signals 
  SIGNAL a1sum12                          : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1sum12                          : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL b2sum12                          : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL typeconvert12                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section12                  : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv12                      : signed(41 DOWNTO 0); -- sfix42_En30
  SIGNAL b1mul12                          : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b2mul12                          : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b3mul12                          : signed(39 DOWNTO 0); -- sfix40_En38
  SIGNAL b1multypeconvert12               : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_44                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_45                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_22                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL add_cast_46                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_cast_47                      : signed(41 DOWNTO 0); -- sfix42_En38
  SIGNAL add_temp_23                      : signed(42 DOWNTO 0); -- sfix43_En38
  SIGNAL output_typeconvert               : signed(48 DOWNTO 0); -- sfix49_En45
  SIGNAL output_register                  : signed(48 DOWNTO 0); -- sfix49_En45


BEGIN

  -- Block Statements
  input_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        input_register <= signed(filter_in);
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  mul_temp <= input_register * scaleconst1;
  scale1 <= resize(mul_temp, 51);

  scaletypeconvert1 <= resize(shift_right(scale1(50 DOWNTO 0) + ( "0" & (scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35) & NOT scale1(35))), 35), 16);

  --   ------------------ Section 1 ------------------

  typeconvert1 <= resize(shift_right(a1sum1(30 DOWNTO 0) + ( "0" & (a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15) & NOT a1sum1(15))), 15), 16);

  delay_process_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section1 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section1(1) <= delay_section1(0);
        delay_section1(0) <= typeconvert1;
      END IF;
    END IF;
  END PROCESS delay_process_section1;

  inputconv1 <= resize(scaletypeconvert1(14 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 42);

  b1mul1 <= typeconvert1 * coeff_b1_section1;

  unaryminus_temp <= ('0' & delay_section1(0)) WHEN delay_section1(0) = "1000000000000000"
      ELSE -resize(delay_section1(0),17);
  b2mul1 <= resize(unaryminus_temp(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b3mul1 <= delay_section1(1) * coeff_b3_section1;

  a1sum1 <= inputconv1;

  b1multypeconvert1 <= resize(b1mul1, 42);

  add_cast <= b1multypeconvert1;
  add_cast_1 <= resize(b2mul1, 42);
  add_temp <= resize(add_cast, 43) + resize(add_cast_1, 43);
  b2sum1 <= add_temp(41 DOWNTO 0);

  add_cast_2 <= b2sum1;
  add_cast_3 <= resize(b3mul1, 42);
  add_temp_1 <= resize(add_cast_2, 43) + resize(add_cast_3, 43);
  b1sum1 <= add_temp_1(41 DOWNTO 0);

  section_result1 <= resize(shift_right(b1sum1(41) & b1sum1(41 DOWNTO 0) + ( "0" & (b1sum1(8) & NOT b1sum1(8) & NOT b1sum1(8) & NOT b1sum1(8) & NOT b1sum1(8) & NOT b1sum1(8) & NOT b1sum1(8) & NOT b1sum1(8))), 8), 42);

  --   ------------------ Section 2 ------------------

  typeconvert2 <= resize(shift_right(a1sum2(30 DOWNTO 0) + ( "0" & (a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15) & NOT a1sum2(15))), 15), 16);

  delay_process_section2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section2 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section2(1) <= delay_section2(0);
        delay_section2(0) <= typeconvert2;
      END IF;
    END IF;
  END PROCESS delay_process_section2;

  inputconv2 <= section_result1;

  b1mul2 <= typeconvert2 * coeff_b1_section2;

  b2mul2 <= delay_section2(0) * coeff_b2_section2;

  b3mul2 <= delay_section2(1) * coeff_b3_section2;

  a1sum2 <= inputconv2;

  b1multypeconvert2 <= resize(b1mul2, 42);

  add_cast_4 <= b1multypeconvert2;
  add_cast_5 <= resize(b2mul2, 42);
  add_temp_2 <= resize(add_cast_4, 43) + resize(add_cast_5, 43);
  b2sum2 <= add_temp_2(41 DOWNTO 0);

  add_cast_6 <= b2sum2;
  add_cast_7 <= resize(b3mul2, 42);
  add_temp_3 <= resize(add_cast_6, 43) + resize(add_cast_7, 43);
  b1sum2 <= add_temp_3(41 DOWNTO 0);

  section_result2 <= resize(shift_right(b1sum2(41) & b1sum2(41 DOWNTO 0) + ( "0" & (b1sum2(8) & NOT b1sum2(8) & NOT b1sum2(8) & NOT b1sum2(8) & NOT b1sum2(8) & NOT b1sum2(8) & NOT b1sum2(8) & NOT b1sum2(8))), 8), 42);

  --   ------------------ Section 3 ------------------

  typeconvert3 <= resize(shift_right(a1sum3(30 DOWNTO 0) + ( "0" & (a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15) & NOT a1sum3(15))), 15), 16);

  delay_process_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section3 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section3(1) <= delay_section3(0);
        delay_section3(0) <= typeconvert3;
      END IF;
    END IF;
  END PROCESS delay_process_section3;

  inputconv3 <= section_result2;

  b1mul3 <= typeconvert3 * coeff_b1_section3;

  unaryminus_temp_1 <= ('0' & delay_section3(0)) WHEN delay_section3(0) = "1000000000000000"
      ELSE -resize(delay_section3(0),17);
  b2mul3 <= resize(unaryminus_temp_1(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b3mul3 <= delay_section3(1) * coeff_b3_section3;

  a1sum3 <= inputconv3;

  b1multypeconvert3 <= resize(b1mul3, 42);

  add_cast_8 <= b1multypeconvert3;
  add_cast_9 <= resize(b2mul3, 42);
  add_temp_4 <= resize(add_cast_8, 43) + resize(add_cast_9, 43);
  b2sum3 <= add_temp_4(41 DOWNTO 0);

  add_cast_10 <= b2sum3;
  add_cast_11 <= resize(b3mul3, 42);
  add_temp_5 <= resize(add_cast_10, 43) + resize(add_cast_11, 43);
  b1sum3 <= add_temp_5(41 DOWNTO 0);

  section_result3 <= resize(shift_right(b1sum3(41) & b1sum3(41 DOWNTO 0) + ( "0" & (b1sum3(8) & NOT b1sum3(8) & NOT b1sum3(8) & NOT b1sum3(8) & NOT b1sum3(8) & NOT b1sum3(8) & NOT b1sum3(8) & NOT b1sum3(8))), 8), 42);

  --   ------------------ Section 4 ------------------

  typeconvert4 <= resize(shift_right(a1sum4(30 DOWNTO 0) + ( "0" & (a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15) & NOT a1sum4(15))), 15), 16);

  delay_process_section4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section4 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section4(1) <= delay_section4(0);
        delay_section4(0) <= typeconvert4;
      END IF;
    END IF;
  END PROCESS delay_process_section4;

  inputconv4 <= section_result3;

  b1mul4 <= typeconvert4 * coeff_b1_section4;

  unaryminus_temp_2 <= ('0' & delay_section4(0)) WHEN delay_section4(0) = "1000000000000000"
      ELSE -resize(delay_section4(0),17);
  b2mul4 <= resize(unaryminus_temp_2(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b3mul4 <= delay_section4(1) * coeff_b3_section4;

  a1sum4 <= inputconv4;

  b1multypeconvert4 <= resize(b1mul4, 42);

  add_cast_12 <= b1multypeconvert4;
  add_cast_13 <= resize(b2mul4, 42);
  add_temp_6 <= resize(add_cast_12, 43) + resize(add_cast_13, 43);
  b2sum4 <= add_temp_6(41 DOWNTO 0);

  add_cast_14 <= b2sum4;
  add_cast_15 <= resize(b3mul4, 42);
  add_temp_7 <= resize(add_cast_14, 43) + resize(add_cast_15, 43);
  b1sum4 <= add_temp_7(41 DOWNTO 0);

  section_result4 <= resize(shift_right(b1sum4(41) & b1sum4(41 DOWNTO 0) + ( "0" & (b1sum4(8) & NOT b1sum4(8) & NOT b1sum4(8) & NOT b1sum4(8) & NOT b1sum4(8) & NOT b1sum4(8) & NOT b1sum4(8) & NOT b1sum4(8))), 8), 42);

  --   ------------------ Section 5 ------------------

  typeconvert5 <= resize(shift_right(a1sum5(30 DOWNTO 0) + ( "0" & (a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15) & NOT a1sum5(15))), 15), 16);

  delay_process_section5 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section5 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section5(1) <= delay_section5(0);
        delay_section5(0) <= typeconvert5;
      END IF;
    END IF;
  END PROCESS delay_process_section5;

  inputconv5 <= section_result4;

  b1mul5 <= typeconvert5 * coeff_b1_section5;

  b2mul5 <= delay_section5(0) * coeff_b2_section5;

  b3mul5 <= delay_section5(1) * coeff_b3_section5;

  a1sum5 <= inputconv5;

  b1multypeconvert5 <= resize(b1mul5, 42);

  add_cast_16 <= b1multypeconvert5;
  add_cast_17 <= resize(b2mul5, 42);
  add_temp_8 <= resize(add_cast_16, 43) + resize(add_cast_17, 43);
  b2sum5 <= add_temp_8(41 DOWNTO 0);

  add_cast_18 <= b2sum5;
  add_cast_19 <= resize(b3mul5, 42);
  add_temp_9 <= resize(add_cast_18, 43) + resize(add_cast_19, 43);
  b1sum5 <= add_temp_9(41 DOWNTO 0);

  section_result5 <= resize(shift_right(b1sum5(41) & b1sum5(41 DOWNTO 0) + ( "0" & (b1sum5(8) & NOT b1sum5(8) & NOT b1sum5(8) & NOT b1sum5(8) & NOT b1sum5(8) & NOT b1sum5(8) & NOT b1sum5(8) & NOT b1sum5(8))), 8), 42);

  --   ------------------ Section 6 ------------------

  typeconvert6 <= resize(shift_right(a1sum6(30 DOWNTO 0) + ( "0" & (a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15) & NOT a1sum6(15))), 15), 16);

  delay_process_section6 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section6 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section6(1) <= delay_section6(0);
        delay_section6(0) <= typeconvert6;
      END IF;
    END IF;
  END PROCESS delay_process_section6;

  inputconv6 <= section_result5;

  b1mul6 <= typeconvert6 * coeff_b1_section6;

  b2mul6 <= delay_section6(0) * coeff_b2_section6;

  b3mul6 <= delay_section6(1) * coeff_b3_section6;

  a1sum6 <= inputconv6;

  b1multypeconvert6 <= resize(b1mul6, 42);

  add_cast_20 <= b1multypeconvert6;
  add_cast_21 <= resize(b2mul6, 42);
  add_temp_10 <= resize(add_cast_20, 43) + resize(add_cast_21, 43);
  b2sum6 <= add_temp_10(41 DOWNTO 0);

  add_cast_22 <= b2sum6;
  add_cast_23 <= resize(b3mul6, 42);
  add_temp_11 <= resize(add_cast_22, 43) + resize(add_cast_23, 43);
  b1sum6 <= add_temp_11(41 DOWNTO 0);

  section_result6 <= resize(shift_right(b1sum6(41) & b1sum6(41 DOWNTO 0) + ( "0" & (b1sum6(8) & NOT b1sum6(8) & NOT b1sum6(8) & NOT b1sum6(8) & NOT b1sum6(8) & NOT b1sum6(8) & NOT b1sum6(8) & NOT b1sum6(8))), 8), 42);

  --   ------------------ Section 7 ------------------

  typeconvert7 <= resize(shift_right(a1sum7(30 DOWNTO 0) + ( "0" & (a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15) & NOT a1sum7(15))), 15), 16);

  delay_process_section7 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section7 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section7(1) <= delay_section7(0);
        delay_section7(0) <= typeconvert7;
      END IF;
    END IF;
  END PROCESS delay_process_section7;

  inputconv7 <= section_result6;

  b1mul7 <= resize(typeconvert7(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b2mul7 <= resize(delay_section7(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b3mul7 <= resize(delay_section7(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  a1sum7 <= inputconv7;

  b1multypeconvert7 <= resize(b1mul7, 42);

  add_cast_24 <= b1multypeconvert7;
  add_cast_25 <= resize(b2mul7, 42);
  add_temp_12 <= resize(add_cast_24, 43) + resize(add_cast_25, 43);
  b2sum7 <= add_temp_12(41 DOWNTO 0);

  add_cast_26 <= b2sum7;
  add_cast_27 <= resize(b3mul7, 42);
  add_temp_13 <= resize(add_cast_26, 43) + resize(add_cast_27, 43);
  b1sum7 <= add_temp_13(41 DOWNTO 0);

  section_result7 <= resize(shift_right(b1sum7(41) & b1sum7(41 DOWNTO 0) + ( "0" & (b1sum7(8) & NOT b1sum7(8) & NOT b1sum7(8) & NOT b1sum7(8) & NOT b1sum7(8) & NOT b1sum7(8) & NOT b1sum7(8) & NOT b1sum7(8))), 8), 42);

  --   ------------------ Section 8 ------------------

  typeconvert8 <= resize(shift_right(a1sum8(30 DOWNTO 0) + ( "0" & (a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15) & NOT a1sum8(15))), 15), 16);

  delay_process_section8 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section8 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section8(1) <= delay_section8(0);
        delay_section8(0) <= typeconvert8;
      END IF;
    END IF;
  END PROCESS delay_process_section8;

  inputconv8 <= section_result7;

  b1mul8 <= resize(typeconvert8(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b2mul8 <= resize(delay_section8(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b3mul8 <= resize(delay_section8(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  a1sum8 <= inputconv8;

  b1multypeconvert8 <= resize(b1mul8, 42);

  add_cast_28 <= b1multypeconvert8;
  add_cast_29 <= resize(b2mul8, 42);
  add_temp_14 <= resize(add_cast_28, 43) + resize(add_cast_29, 43);
  b2sum8 <= add_temp_14(41 DOWNTO 0);

  add_cast_30 <= b2sum8;
  add_cast_31 <= resize(b3mul8, 42);
  add_temp_15 <= resize(add_cast_30, 43) + resize(add_cast_31, 43);
  b1sum8 <= add_temp_15(41 DOWNTO 0);

  section_result8 <= resize(shift_right(b1sum8(41) & b1sum8(41 DOWNTO 0) + ( "0" & (b1sum8(8) & NOT b1sum8(8) & NOT b1sum8(8) & NOT b1sum8(8) & NOT b1sum8(8) & NOT b1sum8(8) & NOT b1sum8(8) & NOT b1sum8(8))), 8), 42);

  --   ------------------ Section 9 ------------------

  typeconvert9 <= resize(shift_right(a1sum9(30 DOWNTO 0) + ( "0" & (a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15) & NOT a1sum9(15))), 15), 16);

  delay_process_section9 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section9 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section9(1) <= delay_section9(0);
        delay_section9(0) <= typeconvert9;
      END IF;
    END IF;
  END PROCESS delay_process_section9;

  inputconv9 <= section_result8;

  b1mul9 <= resize(typeconvert9(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b2mul9 <= resize(delay_section9(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b3mul9 <= resize(delay_section9(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  a1sum9 <= inputconv9;

  b1multypeconvert9 <= resize(b1mul9, 42);

  add_cast_32 <= b1multypeconvert9;
  add_cast_33 <= resize(b2mul9, 42);
  add_temp_16 <= resize(add_cast_32, 43) + resize(add_cast_33, 43);
  b2sum9 <= add_temp_16(41 DOWNTO 0);

  add_cast_34 <= b2sum9;
  add_cast_35 <= resize(b3mul9, 42);
  add_temp_17 <= resize(add_cast_34, 43) + resize(add_cast_35, 43);
  b1sum9 <= add_temp_17(41 DOWNTO 0);

  section_result9 <= resize(shift_right(b1sum9(41) & b1sum9(41 DOWNTO 0) + ( "0" & (b1sum9(8) & NOT b1sum9(8) & NOT b1sum9(8) & NOT b1sum9(8) & NOT b1sum9(8) & NOT b1sum9(8) & NOT b1sum9(8) & NOT b1sum9(8))), 8), 42);

  --   ------------------ Section 10 ------------------

  typeconvert10 <= resize(shift_right(a1sum10(30 DOWNTO 0) + ( "0" & (a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15) & NOT a1sum10(15))), 15), 16);

  delay_process_section10 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section10 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section10(1) <= delay_section10(0);
        delay_section10(0) <= typeconvert10;
      END IF;
    END IF;
  END PROCESS delay_process_section10;

  inputconv10 <= section_result9;

  b1mul10 <= resize(typeconvert10(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b2mul10 <= resize(delay_section10(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b3mul10 <= resize(delay_section10(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  a1sum10 <= inputconv10;

  b1multypeconvert10 <= resize(b1mul10, 42);

  add_cast_36 <= b1multypeconvert10;
  add_cast_37 <= resize(b2mul10, 42);
  add_temp_18 <= resize(add_cast_36, 43) + resize(add_cast_37, 43);
  b2sum10 <= add_temp_18(41 DOWNTO 0);

  add_cast_38 <= b2sum10;
  add_cast_39 <= resize(b3mul10, 42);
  add_temp_19 <= resize(add_cast_38, 43) + resize(add_cast_39, 43);
  b1sum10 <= add_temp_19(41 DOWNTO 0);

  section_result10 <= resize(shift_right(b1sum10(41) & b1sum10(41 DOWNTO 0) + ( "0" & (b1sum10(8) & NOT b1sum10(8) & NOT b1sum10(8) & NOT b1sum10(8) & NOT b1sum10(8) & NOT b1sum10(8) & NOT b1sum10(8) & NOT b1sum10(8))), 8), 42);

  --   ------------------ Section 11 ------------------

  typeconvert11 <= resize(shift_right(a1sum11(30 DOWNTO 0) + ( "0" & (a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15) & NOT a1sum11(15))), 15), 16);

  delay_process_section11 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section11 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section11(1) <= delay_section11(0);
        delay_section11(0) <= typeconvert11;
      END IF;
    END IF;
  END PROCESS delay_process_section11;

  inputconv11 <= section_result10;

  b1mul11 <= resize(typeconvert11(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b2mul11 <= resize(delay_section11(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b3mul11 <= resize(delay_section11(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  a1sum11 <= inputconv11;

  b1multypeconvert11 <= resize(b1mul11, 42);

  add_cast_40 <= b1multypeconvert11;
  add_cast_41 <= resize(b2mul11, 42);
  add_temp_20 <= resize(add_cast_40, 43) + resize(add_cast_41, 43);
  b2sum11 <= add_temp_20(41 DOWNTO 0);

  add_cast_42 <= b2sum11;
  add_cast_43 <= resize(b3mul11, 42);
  add_temp_21 <= resize(add_cast_42, 43) + resize(add_cast_43, 43);
  b1sum11 <= add_temp_21(41 DOWNTO 0);

  section_result11 <= resize(shift_right(b1sum11(41) & b1sum11(41 DOWNTO 0) + ( "0" & (b1sum11(8) & NOT b1sum11(8) & NOT b1sum11(8) & NOT b1sum11(8) & NOT b1sum11(8) & NOT b1sum11(8) & NOT b1sum11(8) & NOT b1sum11(8))), 8), 42);

  --   ------------------ Section 12 ------------------

  typeconvert12 <= resize(shift_right(a1sum12(30 DOWNTO 0) + ( "0" & (a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15) & NOT a1sum12(15))), 15), 16);

  delay_process_section12 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section12 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section12(1) <= delay_section12(0);
        delay_section12(0) <= typeconvert12;
      END IF;
    END IF;
  END PROCESS delay_process_section12;

  inputconv12 <= section_result11;

  b1mul12 <= resize(typeconvert12(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b2mul12 <= resize(delay_section12(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  b3mul12 <= resize(delay_section12(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  a1sum12 <= inputconv12;

  b1multypeconvert12 <= resize(b1mul12, 42);

  add_cast_44 <= b1multypeconvert12;
  add_cast_45 <= resize(b2mul12, 42);
  add_temp_22 <= resize(add_cast_44, 43) + resize(add_cast_45, 43);
  b2sum12 <= add_temp_22(41 DOWNTO 0);

  add_cast_46 <= b2sum12;
  add_cast_47 <= resize(b3mul12, 42);
  add_temp_23 <= resize(add_cast_46, 43) + resize(add_cast_47, 43);
  b1sum12 <= add_temp_23(41 DOWNTO 0);

  output_typeconvert <= resize(b1sum12(41 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 49);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
