-- -------------------------------------------------------------
--
-- Module: iir4
-- Generated by MATLAB(R) 9.11 and Filter Design HDL Coder 3.1.10.
-- Generated on: 2022-04-26 02:52:49
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- Name: iir4
-- TestBenchName: iir4_tb
-- TestBenchStimulus: step ramp chirp 

-- Filter Specifications:
--
-- Sample Rate     : N/A (normalized frequency)
-- Response        : Lowpass
-- Specification   : Fp,Fst,Ap,Ast
-- Passband Ripple : 1 dB
-- Stopband Edge   : 0.5
-- Stopband Atten. : 80 dB
-- Passband Edge   : 0.4
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time IIR Filter (real)
-- -------------------------------
-- Filter Structure    : Direct-Form II, Second-Order Sections
-- Number of Sections  : 4
-- Stable              : Yes
-- Linear Phase        : No
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY iir4 IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    real; -- double
         filter_out                      :   OUT   real  -- double
         );

END iir4;


----------------------------------------------------------------
--Module Architecture: iir4
----------------------------------------------------------------
ARCHITECTURE rtl OF iir4 IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF real; -- double
  -- Constants
  CONSTANT scaleconst1                    : real := 7.2772785363857295E-01; -- double
  CONSTANT coeff_b1_section1              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section1              : real := 8.5242788171298975E-02; -- double
  CONSTANT coeff_b3_section1              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section1              : real := -7.3999391694938854E-01; -- double
  CONSTANT coeff_a3_section1              : real := 8.6096924000547526E-01; -- double
  CONSTANT scaleconst2                    : real := 8.2896081185297854E-01; -- double
  CONSTANT coeff_b1_section2              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section2              : real := 6.9015098142565945E-01; -- double
  CONSTANT coeff_b3_section2              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section2              : real := -1.0374504402647735E+00; -- double
  CONSTANT coeff_a3_section2              : real := 7.0624752625259390E-01; -- double
  CONSTANT scaleconst3                    : real := 1.3493580858904639E+00; -- double
  CONSTANT coeff_b1_section3              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section3              : real := 1.7434235723946381E+00; -- double
  CONSTANT coeff_b3_section3              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section3              : real := -1.3739508673485226E+00; -- double
  CONSTANT coeff_a3_section3              : real := 5.4308194952158750E-01; -- double
  CONSTANT scaleconst4                    : real := 4.7870907237121786E-03; -- double
  CONSTANT coeff_b1_section4              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_b2_section4              : real := -1.3251216431376614E-01; -- double
  CONSTANT coeff_b3_section4              : real := 1.0000000000000000E+00; -- double
  CONSTANT coeff_a2_section4              : real := -6.0829774354443655E-01; -- double
  CONSTANT coeff_a3_section4              : real := 9.6051992352852389E-01; -- double
  -- Signals
  SIGNAL input_register                   : real := 0.0; -- double
  SIGNAL scale1                           : real := 0.0; -- double
  SIGNAL scaletypeconvert1                : real := 0.0; -- double
  -- Section 1 Signals 
  SIGNAL a1sum1                           : real := 0.0; -- double
  SIGNAL a2sum1                           : real := 0.0; -- double
  SIGNAL b1sum1                           : real := 0.0; -- double
  SIGNAL b2sum1                           : real := 0.0; -- double
  SIGNAL delay_section1                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv1                       : real := 0.0; -- double
  SIGNAL a2mul1                           : real := 0.0; -- double
  SIGNAL a3mul1                           : real := 0.0; -- double
  SIGNAL b1mul1                           : real := 0.0; -- double
  SIGNAL b2mul1                           : real := 0.0; -- double
  SIGNAL b3mul1                           : real := 0.0; -- double
  SIGNAL scale2                           : real := 0.0; -- double
  SIGNAL scaletypeconvert2                : real := 0.0; -- double
  -- Section 2 Signals 
  SIGNAL a1sum2                           : real := 0.0; -- double
  SIGNAL a2sum2                           : real := 0.0; -- double
  SIGNAL b1sum2                           : real := 0.0; -- double
  SIGNAL b2sum2                           : real := 0.0; -- double
  SIGNAL delay_section2                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv2                       : real := 0.0; -- double
  SIGNAL a2mul2                           : real := 0.0; -- double
  SIGNAL a3mul2                           : real := 0.0; -- double
  SIGNAL b1mul2                           : real := 0.0; -- double
  SIGNAL b2mul2                           : real := 0.0; -- double
  SIGNAL b3mul2                           : real := 0.0; -- double
  SIGNAL scale3                           : real := 0.0; -- double
  SIGNAL scaletypeconvert3                : real := 0.0; -- double
  -- Section 3 Signals 
  SIGNAL a1sum3                           : real := 0.0; -- double
  SIGNAL a2sum3                           : real := 0.0; -- double
  SIGNAL b1sum3                           : real := 0.0; -- double
  SIGNAL b2sum3                           : real := 0.0; -- double
  SIGNAL delay_section3                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv3                       : real := 0.0; -- double
  SIGNAL a2mul3                           : real := 0.0; -- double
  SIGNAL a3mul3                           : real := 0.0; -- double
  SIGNAL b1mul3                           : real := 0.0; -- double
  SIGNAL b2mul3                           : real := 0.0; -- double
  SIGNAL b3mul3                           : real := 0.0; -- double
  SIGNAL scale4                           : real := 0.0; -- double
  SIGNAL scaletypeconvert4                : real := 0.0; -- double
  -- Section 4 Signals 
  SIGNAL a1sum4                           : real := 0.0; -- double
  SIGNAL a2sum4                           : real := 0.0; -- double
  SIGNAL b1sum4                           : real := 0.0; -- double
  SIGNAL b2sum4                           : real := 0.0; -- double
  SIGNAL delay_section4                   : delay_pipeline_type(0 TO 1) := (0.0, 0.0); -- double
  SIGNAL inputconv4                       : real := 0.0; -- double
  SIGNAL a2mul4                           : real := 0.0; -- double
  SIGNAL a3mul4                           : real := 0.0; -- double
  SIGNAL b1mul4                           : real := 0.0; -- double
  SIGNAL b2mul4                           : real := 0.0; -- double
  SIGNAL b3mul4                           : real := 0.0; -- double
  SIGNAL output_typeconvert               : real := 0.0; -- double
  SIGNAL output_register                  : real := 0.0; -- double


BEGIN

  -- Block Statements
  input_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_register <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        input_register <= filter_in;
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  scale1 <= input_register * scaleconst1;

  scaletypeconvert1 <= scale1;


  --   ------------------ Section 1 ------------------

  delay_process_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section1(0) <= 0.0000000000000000E+00;
      delay_section1(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section1(1) <= delay_section1(0);
        delay_section1(0) <= a1sum1;
      END IF;
    END IF;
  END PROCESS delay_process_section1;

  inputconv1 <= scaletypeconvert1;


  a2mul1 <= delay_section1(0) * coeff_a2_section1;

  a3mul1 <= delay_section1(1) * coeff_a3_section1;

  b1mul1 <= a1sum1;


  b2mul1 <= delay_section1(0) * coeff_b2_section1;

  b3mul1 <= delay_section1(1);


  a2sum1 <= inputconv1 - a2mul1;

  a1sum1 <= a2sum1 - a3mul1;

  b2sum1 <= b1mul1 + b2mul1;

  b1sum1 <= b2sum1 + b3mul1;

  scale2 <= b1sum1 * scaleconst2;

  scaletypeconvert2 <= scale2;


  --   ------------------ Section 2 ------------------

  delay_process_section2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section2(0) <= 0.0000000000000000E+00;
      delay_section2(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section2(1) <= delay_section2(0);
        delay_section2(0) <= a1sum2;
      END IF;
    END IF;
  END PROCESS delay_process_section2;

  inputconv2 <= scaletypeconvert2;


  a2mul2 <= delay_section2(0) * coeff_a2_section2;

  a3mul2 <= delay_section2(1) * coeff_a3_section2;

  b1mul2 <= a1sum2;


  b2mul2 <= delay_section2(0) * coeff_b2_section2;

  b3mul2 <= delay_section2(1);


  a2sum2 <= inputconv2 - a2mul2;

  a1sum2 <= a2sum2 - a3mul2;

  b2sum2 <= b1mul2 + b2mul2;

  b1sum2 <= b2sum2 + b3mul2;

  scale3 <= b1sum2 * scaleconst3;

  scaletypeconvert3 <= scale3;


  --   ------------------ Section 3 ------------------

  delay_process_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section3(0) <= 0.0000000000000000E+00;
      delay_section3(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section3(1) <= delay_section3(0);
        delay_section3(0) <= a1sum3;
      END IF;
    END IF;
  END PROCESS delay_process_section3;

  inputconv3 <= scaletypeconvert3;


  a2mul3 <= delay_section3(0) * coeff_a2_section3;

  a3mul3 <= delay_section3(1) * coeff_a3_section3;

  b1mul3 <= a1sum3;


  b2mul3 <= delay_section3(0) * coeff_b2_section3;

  b3mul3 <= delay_section3(1);


  a2sum3 <= inputconv3 - a2mul3;

  a1sum3 <= a2sum3 - a3mul3;

  b2sum3 <= b1mul3 + b2mul3;

  b1sum3 <= b2sum3 + b3mul3;

  scale4 <= b1sum3 * scaleconst4;

  scaletypeconvert4 <= scale4;


  --   ------------------ Section 4 ------------------

  delay_process_section4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section4(0) <= 0.0000000000000000E+00;
      delay_section4(1) <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section4(1) <= delay_section4(0);
        delay_section4(0) <= a1sum4;
      END IF;
    END IF;
  END PROCESS delay_process_section4;

  inputconv4 <= scaletypeconvert4;


  a2mul4 <= delay_section4(0) * coeff_a2_section4;

  a3mul4 <= delay_section4(1) * coeff_a3_section4;

  b1mul4 <= a1sum4;


  b2mul4 <= delay_section4(0) * coeff_b2_section4;

  b3mul4 <= delay_section4(1);


  a2sum4 <= inputconv4 - a2mul4;

  a1sum4 <= a2sum4 - a3mul4;

  b2sum4 <= b1mul4 + b2mul4;

  b1sum4 <= b2sum4 + b3mul4;

  output_typeconvert <= b1sum4;


  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= output_register;
END rtl;
