-- -------------------------------------------------------------
--
-- Module: bandpass_leastPth
-- Generated by MATLAB(R) 9.11 and Filter Design HDL Coder 3.1.10.
-- Generated on: 2022-05-01 14:42:30
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- InputType: signed/unsigned
-- OptimizeForHDL: on
-- Name: bandpass_leastPth
-- TestBenchName: bandpass_leastPth_tb
-- TestBenchStimulus: step ramp chirp 
-- ClockHighTime: 10
-- ClockLowTime: 10

-- Filter Specifications:
--
-- Sample Rate            : N/A (normalized frequency)
-- Response               : Bandpass
-- Specification          : Fst1,Fp1,Fp2,Fst2,Ast1,Ap,Ast2
-- First Stopband Edge    : 0.35
-- Second Stopband Atten. : 60 dB
-- Passband Ripple        : 1 dB
-- Second Passband Edge   : 0.55
-- First Passband Edge    : 0.45
-- Second Stopband Edge   : 0.65
-- First Stopband Atten.  : 60 dB
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time IIR Filter (real)
-- -------------------------------
-- Filter Structure    : Direct-Form II, Second-Order Sections
-- Number of Sections  : 12
-- Stable              : Yes
-- Linear Phase        : No
-- Arithmetic          : fixed
-- Numerator           : s24,21 -> [-4 4)
-- Denominator         : s24,22 -> [-2 2)
-- Scale Values        : s24,34 -> [-4.882812e-04 4.882812e-04)
-- Input               : s24,23 -> [-1 1)
-- Section Input       : s24,28 -> [-3.125000e-02 3.125000e-02)
-- Section Output      : s24,18 -> [-32 32)
-- Output              : s24,18 -> [-32 32)
-- State               : s24,23 -> [-1 1)
-- Numerator Prod      : s48,44 -> [-8 8)
-- Denominator Prod    : s48,45 -> [-4 4)
-- Numerator Accum     : s40,34 -> [-32 32)
-- Denominator Accum   : s40,35 -> [-16 16)
-- Round Mode          : convergent
-- Overflow Mode       : wrap
-- Cast Before Sum     : true
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY bandpass_leastPth IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    signed(23 DOWNTO 0); -- sfix24_En23
         filter_out                      :   OUT   signed(23 DOWNTO 0)  -- sfix24_En18
         );

END bandpass_leastPth;


----------------------------------------------------------------
--Module Architecture: bandpass_leastPth
----------------------------------------------------------------
ARCHITECTURE rtl OF bandpass_leastPth IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(23 DOWNTO 0); -- sfix24_En23
  -- Constants
  CONSTANT scaleconst1                    : signed(23 DOWNTO 0) := to_signed(-5378500, 24); -- sfix24_En34
  CONSTANT coeff_b1_section1              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section1              : signed(23 DOWNTO 0) := to_signed(-3035016, 24); -- sfix24_En21
  CONSTANT coeff_b3_section1              : signed(23 DOWNTO 0) := to_signed(937984, 24); -- sfix24_En21
  CONSTANT coeff_a2_section1              : signed(23 DOWNTO 0) := to_signed(-7872029, 24); -- sfix24_En22
  CONSTANT coeff_a3_section1              : signed(23 DOWNTO 0) := to_signed(3789481, 24); -- sfix24_En22
  CONSTANT coeff_b1_section2              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section2              : signed(23 DOWNTO 0) := to_signed(1204761, 24); -- sfix24_En21
  CONSTANT coeff_b3_section2              : signed(23 DOWNTO 0) := to_signed(50934, 24); -- sfix24_En21
  CONSTANT coeff_a2_section2              : signed(23 DOWNTO 0) := to_signed(-7997988, 24); -- sfix24_En22
  CONSTANT coeff_a3_section2              : signed(23 DOWNTO 0) := to_signed(4097414, 24); -- sfix24_En22
  CONSTANT coeff_b1_section3              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section3              : signed(23 DOWNTO 0) := to_signed(-3976269, 24); -- sfix24_En21
  CONSTANT coeff_b3_section3              : signed(23 DOWNTO 0) := to_signed(2095559, 24); -- sfix24_En21
  CONSTANT coeff_a2_section3              : signed(23 DOWNTO 0) := to_signed(-7853728, 24); -- sfix24_En22
  CONSTANT coeff_a3_section3              : signed(23 DOWNTO 0) := to_signed(3882432, 24); -- sfix24_En22
  CONSTANT coeff_b1_section4              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section4              : signed(23 DOWNTO 0) := to_signed(-2292894, 24); -- sfix24_En21
  CONSTANT coeff_b3_section4              : signed(23 DOWNTO 0) := to_signed(197268, 24); -- sfix24_En21
  CONSTANT coeff_a2_section4              : signed(23 DOWNTO 0) := to_signed(-8105746, 24); -- sfix24_En22
  CONSTANT coeff_a3_section4              : signed(23 DOWNTO 0) := to_signed(3953896, 24); -- sfix24_En22
  CONSTANT coeff_b1_section5              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section5              : signed(23 DOWNTO 0) := to_signed(-273297, 24); -- sfix24_En21
  CONSTANT coeff_b3_section5              : signed(23 DOWNTO 0) := to_signed(785866, 24); -- sfix24_En21
  CONSTANT coeff_a2_section5              : signed(23 DOWNTO 0) := to_signed(-8298167, 24); -- sfix24_En22
  CONSTANT coeff_a3_section5              : signed(23 DOWNTO 0) := to_signed(4127562, 24); -- sfix24_En22
  CONSTANT coeff_b1_section6              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section6              : signed(23 DOWNTO 0) := to_signed(-5693746, 24); -- sfix24_En21
  CONSTANT coeff_b3_section6              : signed(23 DOWNTO 0) := to_signed(5017121, 24); -- sfix24_En21
  CONSTANT coeff_a2_section6              : signed(23 DOWNTO 0) := to_signed(-1605212, 24); -- sfix24_En22
  CONSTANT coeff_a3_section6              : signed(23 DOWNTO 0) := to_signed(483623, 24); -- sfix24_En22
  CONSTANT coeff_b1_section7              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section7              : signed(23 DOWNTO 0) := to_signed(-1798274, 24); -- sfix24_En21
  CONSTANT coeff_b3_section7              : signed(23 DOWNTO 0) := to_signed(1199753, 24); -- sfix24_En21
  CONSTANT coeff_a2_section7              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_a3_section7              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_b1_section8              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section8              : signed(23 DOWNTO 0) := to_signed(-3300846, 24); -- sfix24_En21
  CONSTANT coeff_b3_section8              : signed(23 DOWNTO 0) := to_signed(1204219, 24); -- sfix24_En21
  CONSTANT coeff_a2_section8              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_a3_section8              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_b1_section9              : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section9              : signed(23 DOWNTO 0) := to_signed(714375, 24); -- sfix24_En21
  CONSTANT coeff_b3_section9              : signed(23 DOWNTO 0) := to_signed(40020, 24); -- sfix24_En21
  CONSTANT coeff_a2_section9              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_a3_section9              : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_b1_section10             : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section10             : signed(23 DOWNTO 0) := to_signed(638927, 24); -- sfix24_En21
  CONSTANT coeff_b3_section10             : signed(23 DOWNTO 0) := to_signed(7575, 24); -- sfix24_En21
  CONSTANT coeff_a2_section10             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_a3_section10             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_b1_section11             : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section11             : signed(23 DOWNTO 0) := to_signed(-20279, 24); -- sfix24_En21
  CONSTANT coeff_b3_section11             : signed(23 DOWNTO 0) := to_signed(388, 24); -- sfix24_En21
  CONSTANT coeff_a2_section11             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_a3_section11             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_b1_section12             : signed(23 DOWNTO 0) := to_signed(2097152, 24); -- sfix24_En21
  CONSTANT coeff_b2_section12             : signed(23 DOWNTO 0) := to_signed(-2200824, 24); -- sfix24_En21
  CONSTANT coeff_b3_section12             : signed(23 DOWNTO 0) := to_signed(104020, 24); -- sfix24_En21
  CONSTANT coeff_a2_section12             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  CONSTANT coeff_a3_section12             : signed(23 DOWNTO 0) := to_signed(0, 24); -- sfix24_En22
  -- Signals
  SIGNAL input_register                   : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL scale1                           : signed(52 DOWNTO 0); -- sfix53_En57
  SIGNAL mul_temp                         : signed(47 DOWNTO 0); -- sfix48_En57
  SIGNAL scaletypeconvert1                : signed(23 DOWNTO 0); -- sfix24_En28
  -- Section 1 Signals 
  SIGNAL a1sum1                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2sum1                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum1                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum1                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert1                     : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section1                   : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv1                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2mul1                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL a3mul1                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL b2mul1                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul1                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL sub_cast                         : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_1                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp                         : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL sub_cast_2                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_3                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_1                       : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL b1multypeconvert1                : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast                         : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_1                       : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp                         : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_2                       : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_3                       : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_1                       : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result1                  : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 2 Signals 
  SIGNAL a1sum2                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2sum2                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum2                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum2                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert2                     : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section2                   : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv2                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2mul2                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL a3mul2                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL b2mul2                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul2                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL sub_cast_4                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_5                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_2                       : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL sub_cast_6                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_7                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_3                       : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL b1multypeconvert2                : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_4                       : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_5                       : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_2                       : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_6                       : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_7                       : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_3                       : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result2                  : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 3 Signals 
  SIGNAL a1sum3                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2sum3                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum3                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum3                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert3                     : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section3                   : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv3                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2mul3                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL a3mul3                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL b2mul3                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul3                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL sub_cast_8                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_9                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_4                       : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL sub_cast_10                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_11                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_5                       : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL b1multypeconvert3                : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_8                       : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_9                       : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_4                       : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_10                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_11                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_5                       : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result3                  : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 4 Signals 
  SIGNAL a1sum4                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2sum4                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum4                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum4                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert4                     : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section4                   : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv4                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2mul4                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL a3mul4                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL b2mul4                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul4                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL sub_cast_12                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_13                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_6                       : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL sub_cast_14                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_15                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_7                       : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL b1multypeconvert4                : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_12                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_13                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_6                       : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_14                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_15                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_7                       : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result4                  : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 5 Signals 
  SIGNAL a1sum5                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2sum5                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum5                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum5                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert5                     : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section5                   : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv5                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2mul5                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL a3mul5                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL b2mul5                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul5                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL sub_cast_16                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_17                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_8                       : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL sub_cast_18                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_19                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_9                       : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL b1multypeconvert5                : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_16                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_17                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_8                       : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_18                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_19                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_9                       : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result5                  : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 6 Signals 
  SIGNAL a1sum6                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2sum6                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum6                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum6                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert6                     : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section6                   : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv6                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL a2mul6                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL a3mul6                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL b2mul6                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul6                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL sub_cast_20                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_21                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_10                      : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL sub_cast_22                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_cast_23                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL sub_temp_11                      : signed(40 DOWNTO 0); -- sfix41_En35
  SIGNAL b1multypeconvert6                : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_20                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_21                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_10                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_22                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_23                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_11                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result6                  : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 7 Signals 
  SIGNAL a1sum7                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum7                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum7                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert7                     : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section7                   : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv7                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b2mul7                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul7                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b1multypeconvert7                : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_24                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_25                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_12                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_26                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_27                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_13                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result7                  : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 8 Signals 
  SIGNAL a1sum8                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum8                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum8                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert8                     : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section8                   : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv8                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b2mul8                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul8                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b1multypeconvert8                : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_28                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_29                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_14                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_30                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_31                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_15                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result8                  : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 9 Signals 
  SIGNAL a1sum9                           : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum9                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum9                           : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert9                     : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section9                   : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv9                       : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b2mul9                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul9                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b1multypeconvert9                : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_32                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_33                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_16                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_34                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_35                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_17                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result9                  : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 10 Signals 
  SIGNAL a1sum10                          : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum10                          : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum10                          : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert10                    : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section10                  : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv10                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b2mul10                          : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul10                          : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b1multypeconvert10               : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_36                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_37                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_18                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_38                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_39                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_19                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result10                 : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 11 Signals 
  SIGNAL a1sum11                          : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum11                          : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum11                          : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert11                    : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section11                  : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv11                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b2mul11                          : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul11                          : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b1multypeconvert11               : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_40                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_41                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_20                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_42                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_43                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_21                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL section_result11                 : signed(39 DOWNTO 0); -- sfix40_En35
  -- Section 12 Signals 
  SIGNAL a1sum12                          : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b1sum12                          : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL b2sum12                          : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL typeconvert12                    : signed(23 DOWNTO 0); -- sfix24_En23
  SIGNAL delay_section12                  : delay_pipeline_type(0 TO 1); -- sfix24_En23
  SIGNAL inputconv12                      : signed(39 DOWNTO 0); -- sfix40_En35
  SIGNAL b2mul12                          : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul12                          : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b1multypeconvert12               : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_44                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_45                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_22                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL add_cast_46                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_cast_47                      : signed(39 DOWNTO 0); -- sfix40_En34
  SIGNAL add_temp_23                      : signed(40 DOWNTO 0); -- sfix41_En34
  SIGNAL output_typeconvert               : signed(23 DOWNTO 0); -- sfix24_En18
  SIGNAL output_register                  : signed(23 DOWNTO 0); -- sfix24_En18


BEGIN

  -- Block Statements
  input_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        input_register <= filter_in;
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  mul_temp <= input_register * scaleconst1;
  scale1 <= resize(mul_temp, 53);

  scaletypeconvert1 <= resize(shift_right(scale1(52 DOWNTO 0) + ( "0" & (scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29) & NOT scale1(29))), 29), 24);

  --   ------------------ Section 1 ------------------

  typeconvert1 <= resize(shift_right(a1sum1(35 DOWNTO 0) + ( "0" & (a1sum1(12) & NOT a1sum1(12) & NOT a1sum1(12) & NOT a1sum1(12) & NOT a1sum1(12) & NOT a1sum1(12) & NOT a1sum1(12) & NOT a1sum1(12) & NOT a1sum1(12) & NOT a1sum1(12) & NOT a1sum1(12) & NOT a1sum1(12))), 12), 24);

  delay_process_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section1 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section1(1) <= delay_section1(0);
        delay_section1(0) <= typeconvert1;
      END IF;
    END IF;
  END PROCESS delay_process_section1;

  inputconv1 <= resize(scaletypeconvert1(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  a2mul1 <= delay_section1(0) * coeff_a2_section1;

  a3mul1 <= delay_section1(1) * coeff_a3_section1;

  b2mul1 <= delay_section1(0) * coeff_b2_section1;

  b3mul1 <= delay_section1(1) * coeff_b3_section1;

  sub_cast <= inputconv1;
  sub_cast_1 <= resize(shift_right(a2mul1(47) & a2mul1(47 DOWNTO 0) + ( "0" & (a2mul1(10) & NOT a2mul1(10) & NOT a2mul1(10) & NOT a2mul1(10) & NOT a2mul1(10) & NOT a2mul1(10) & NOT a2mul1(10) & NOT a2mul1(10) & NOT a2mul1(10) & NOT a2mul1(10))), 10), 40);
  sub_temp <= resize(sub_cast, 41) - resize(sub_cast_1, 41);
  a2sum1 <= sub_temp(39 DOWNTO 0);

  sub_cast_2 <= a2sum1;
  sub_cast_3 <= resize(shift_right(a3mul1(47) & a3mul1(47 DOWNTO 0) + ( "0" & (a3mul1(10) & NOT a3mul1(10) & NOT a3mul1(10) & NOT a3mul1(10) & NOT a3mul1(10) & NOT a3mul1(10) & NOT a3mul1(10) & NOT a3mul1(10) & NOT a3mul1(10) & NOT a3mul1(10))), 10), 40);
  sub_temp_1 <= resize(sub_cast_2, 41) - resize(sub_cast_3, 41);
  a1sum1 <= sub_temp_1(39 DOWNTO 0);

  b1multypeconvert1 <= resize(typeconvert1(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast <= b1multypeconvert1;
  add_cast_1 <= resize(shift_right(b2mul1(47) & b2mul1(47 DOWNTO 0) + ( "0" & (b2mul1(10) & NOT b2mul1(10) & NOT b2mul1(10) & NOT b2mul1(10) & NOT b2mul1(10) & NOT b2mul1(10) & NOT b2mul1(10) & NOT b2mul1(10) & NOT b2mul1(10) & NOT b2mul1(10))), 10), 40);
  add_temp <= resize(add_cast, 41) + resize(add_cast_1, 41);
  b2sum1 <= add_temp(39 DOWNTO 0);

  add_cast_2 <= b2sum1;
  add_cast_3 <= resize(shift_right(b3mul1(47) & b3mul1(47 DOWNTO 0) + ( "0" & (b3mul1(10) & NOT b3mul1(10) & NOT b3mul1(10) & NOT b3mul1(10) & NOT b3mul1(10) & NOT b3mul1(10) & NOT b3mul1(10) & NOT b3mul1(10) & NOT b3mul1(10) & NOT b3mul1(10))), 10), 40);
  add_temp_1 <= resize(add_cast_2, 41) + resize(add_cast_3, 41);
  b1sum1 <= add_temp_1(39 DOWNTO 0);

  section_result1 <= resize(b1sum1(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 2 ------------------

  typeconvert2 <= resize(shift_right(a1sum2(35 DOWNTO 0) + ( "0" & (a1sum2(12) & NOT a1sum2(12) & NOT a1sum2(12) & NOT a1sum2(12) & NOT a1sum2(12) & NOT a1sum2(12) & NOT a1sum2(12) & NOT a1sum2(12) & NOT a1sum2(12) & NOT a1sum2(12) & NOT a1sum2(12) & NOT a1sum2(12))), 12), 24);

  delay_process_section2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section2 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section2(1) <= delay_section2(0);
        delay_section2(0) <= typeconvert2;
      END IF;
    END IF;
  END PROCESS delay_process_section2;

  inputconv2 <= section_result1;

  a2mul2 <= delay_section2(0) * coeff_a2_section2;

  a3mul2 <= delay_section2(1) * coeff_a3_section2;

  b2mul2 <= delay_section2(0) * coeff_b2_section2;

  b3mul2 <= delay_section2(1) * coeff_b3_section2;

  sub_cast_4 <= inputconv2;
  sub_cast_5 <= resize(shift_right(a2mul2(47) & a2mul2(47 DOWNTO 0) + ( "0" & (a2mul2(10) & NOT a2mul2(10) & NOT a2mul2(10) & NOT a2mul2(10) & NOT a2mul2(10) & NOT a2mul2(10) & NOT a2mul2(10) & NOT a2mul2(10) & NOT a2mul2(10) & NOT a2mul2(10))), 10), 40);
  sub_temp_2 <= resize(sub_cast_4, 41) - resize(sub_cast_5, 41);
  a2sum2 <= sub_temp_2(39 DOWNTO 0);

  sub_cast_6 <= a2sum2;
  sub_cast_7 <= resize(shift_right(a3mul2(47) & a3mul2(47 DOWNTO 0) + ( "0" & (a3mul2(10) & NOT a3mul2(10) & NOT a3mul2(10) & NOT a3mul2(10) & NOT a3mul2(10) & NOT a3mul2(10) & NOT a3mul2(10) & NOT a3mul2(10) & NOT a3mul2(10) & NOT a3mul2(10))), 10), 40);
  sub_temp_3 <= resize(sub_cast_6, 41) - resize(sub_cast_7, 41);
  a1sum2 <= sub_temp_3(39 DOWNTO 0);

  b1multypeconvert2 <= resize(typeconvert2(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_4 <= b1multypeconvert2;
  add_cast_5 <= resize(shift_right(b2mul2(47) & b2mul2(47 DOWNTO 0) + ( "0" & (b2mul2(10) & NOT b2mul2(10) & NOT b2mul2(10) & NOT b2mul2(10) & NOT b2mul2(10) & NOT b2mul2(10) & NOT b2mul2(10) & NOT b2mul2(10) & NOT b2mul2(10) & NOT b2mul2(10))), 10), 40);
  add_temp_2 <= resize(add_cast_4, 41) + resize(add_cast_5, 41);
  b2sum2 <= add_temp_2(39 DOWNTO 0);

  add_cast_6 <= b2sum2;
  add_cast_7 <= resize(shift_right(b3mul2(47) & b3mul2(47 DOWNTO 0) + ( "0" & (b3mul2(10) & NOT b3mul2(10) & NOT b3mul2(10) & NOT b3mul2(10) & NOT b3mul2(10) & NOT b3mul2(10) & NOT b3mul2(10) & NOT b3mul2(10) & NOT b3mul2(10) & NOT b3mul2(10))), 10), 40);
  add_temp_3 <= resize(add_cast_6, 41) + resize(add_cast_7, 41);
  b1sum2 <= add_temp_3(39 DOWNTO 0);

  section_result2 <= resize(b1sum2(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 3 ------------------

  typeconvert3 <= resize(shift_right(a1sum3(35 DOWNTO 0) + ( "0" & (a1sum3(12) & NOT a1sum3(12) & NOT a1sum3(12) & NOT a1sum3(12) & NOT a1sum3(12) & NOT a1sum3(12) & NOT a1sum3(12) & NOT a1sum3(12) & NOT a1sum3(12) & NOT a1sum3(12) & NOT a1sum3(12) & NOT a1sum3(12))), 12), 24);

  delay_process_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section3 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section3(1) <= delay_section3(0);
        delay_section3(0) <= typeconvert3;
      END IF;
    END IF;
  END PROCESS delay_process_section3;

  inputconv3 <= section_result2;

  a2mul3 <= delay_section3(0) * coeff_a2_section3;

  a3mul3 <= delay_section3(1) * coeff_a3_section3;

  b2mul3 <= delay_section3(0) * coeff_b2_section3;

  b3mul3 <= delay_section3(1) * coeff_b3_section3;

  sub_cast_8 <= inputconv3;
  sub_cast_9 <= resize(shift_right(a2mul3(47) & a2mul3(47 DOWNTO 0) + ( "0" & (a2mul3(10) & NOT a2mul3(10) & NOT a2mul3(10) & NOT a2mul3(10) & NOT a2mul3(10) & NOT a2mul3(10) & NOT a2mul3(10) & NOT a2mul3(10) & NOT a2mul3(10) & NOT a2mul3(10))), 10), 40);
  sub_temp_4 <= resize(sub_cast_8, 41) - resize(sub_cast_9, 41);
  a2sum3 <= sub_temp_4(39 DOWNTO 0);

  sub_cast_10 <= a2sum3;
  sub_cast_11 <= resize(shift_right(a3mul3(47) & a3mul3(47 DOWNTO 0) + ( "0" & (a3mul3(10) & NOT a3mul3(10) & NOT a3mul3(10) & NOT a3mul3(10) & NOT a3mul3(10) & NOT a3mul3(10) & NOT a3mul3(10) & NOT a3mul3(10) & NOT a3mul3(10) & NOT a3mul3(10))), 10), 40);
  sub_temp_5 <= resize(sub_cast_10, 41) - resize(sub_cast_11, 41);
  a1sum3 <= sub_temp_5(39 DOWNTO 0);

  b1multypeconvert3 <= resize(typeconvert3(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_8 <= b1multypeconvert3;
  add_cast_9 <= resize(shift_right(b2mul3(47) & b2mul3(47 DOWNTO 0) + ( "0" & (b2mul3(10) & NOT b2mul3(10) & NOT b2mul3(10) & NOT b2mul3(10) & NOT b2mul3(10) & NOT b2mul3(10) & NOT b2mul3(10) & NOT b2mul3(10) & NOT b2mul3(10) & NOT b2mul3(10))), 10), 40);
  add_temp_4 <= resize(add_cast_8, 41) + resize(add_cast_9, 41);
  b2sum3 <= add_temp_4(39 DOWNTO 0);

  add_cast_10 <= b2sum3;
  add_cast_11 <= resize(shift_right(b3mul3(47) & b3mul3(47 DOWNTO 0) + ( "0" & (b3mul3(10) & NOT b3mul3(10) & NOT b3mul3(10) & NOT b3mul3(10) & NOT b3mul3(10) & NOT b3mul3(10) & NOT b3mul3(10) & NOT b3mul3(10) & NOT b3mul3(10) & NOT b3mul3(10))), 10), 40);
  add_temp_5 <= resize(add_cast_10, 41) + resize(add_cast_11, 41);
  b1sum3 <= add_temp_5(39 DOWNTO 0);

  section_result3 <= resize(b1sum3(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 4 ------------------

  typeconvert4 <= resize(shift_right(a1sum4(35 DOWNTO 0) + ( "0" & (a1sum4(12) & NOT a1sum4(12) & NOT a1sum4(12) & NOT a1sum4(12) & NOT a1sum4(12) & NOT a1sum4(12) & NOT a1sum4(12) & NOT a1sum4(12) & NOT a1sum4(12) & NOT a1sum4(12) & NOT a1sum4(12) & NOT a1sum4(12))), 12), 24);

  delay_process_section4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section4 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section4(1) <= delay_section4(0);
        delay_section4(0) <= typeconvert4;
      END IF;
    END IF;
  END PROCESS delay_process_section4;

  inputconv4 <= section_result3;

  a2mul4 <= delay_section4(0) * coeff_a2_section4;

  a3mul4 <= delay_section4(1) * coeff_a3_section4;

  b2mul4 <= delay_section4(0) * coeff_b2_section4;

  b3mul4 <= delay_section4(1) * coeff_b3_section4;

  sub_cast_12 <= inputconv4;
  sub_cast_13 <= resize(shift_right(a2mul4(47) & a2mul4(47 DOWNTO 0) + ( "0" & (a2mul4(10) & NOT a2mul4(10) & NOT a2mul4(10) & NOT a2mul4(10) & NOT a2mul4(10) & NOT a2mul4(10) & NOT a2mul4(10) & NOT a2mul4(10) & NOT a2mul4(10) & NOT a2mul4(10))), 10), 40);
  sub_temp_6 <= resize(sub_cast_12, 41) - resize(sub_cast_13, 41);
  a2sum4 <= sub_temp_6(39 DOWNTO 0);

  sub_cast_14 <= a2sum4;
  sub_cast_15 <= resize(shift_right(a3mul4(47) & a3mul4(47 DOWNTO 0) + ( "0" & (a3mul4(10) & NOT a3mul4(10) & NOT a3mul4(10) & NOT a3mul4(10) & NOT a3mul4(10) & NOT a3mul4(10) & NOT a3mul4(10) & NOT a3mul4(10) & NOT a3mul4(10) & NOT a3mul4(10))), 10), 40);
  sub_temp_7 <= resize(sub_cast_14, 41) - resize(sub_cast_15, 41);
  a1sum4 <= sub_temp_7(39 DOWNTO 0);

  b1multypeconvert4 <= resize(typeconvert4(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_12 <= b1multypeconvert4;
  add_cast_13 <= resize(shift_right(b2mul4(47) & b2mul4(47 DOWNTO 0) + ( "0" & (b2mul4(10) & NOT b2mul4(10) & NOT b2mul4(10) & NOT b2mul4(10) & NOT b2mul4(10) & NOT b2mul4(10) & NOT b2mul4(10) & NOT b2mul4(10) & NOT b2mul4(10) & NOT b2mul4(10))), 10), 40);
  add_temp_6 <= resize(add_cast_12, 41) + resize(add_cast_13, 41);
  b2sum4 <= add_temp_6(39 DOWNTO 0);

  add_cast_14 <= b2sum4;
  add_cast_15 <= resize(shift_right(b3mul4(47) & b3mul4(47 DOWNTO 0) + ( "0" & (b3mul4(10) & NOT b3mul4(10) & NOT b3mul4(10) & NOT b3mul4(10) & NOT b3mul4(10) & NOT b3mul4(10) & NOT b3mul4(10) & NOT b3mul4(10) & NOT b3mul4(10) & NOT b3mul4(10))), 10), 40);
  add_temp_7 <= resize(add_cast_14, 41) + resize(add_cast_15, 41);
  b1sum4 <= add_temp_7(39 DOWNTO 0);

  section_result4 <= resize(b1sum4(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 5 ------------------

  typeconvert5 <= resize(shift_right(a1sum5(35 DOWNTO 0) + ( "0" & (a1sum5(12) & NOT a1sum5(12) & NOT a1sum5(12) & NOT a1sum5(12) & NOT a1sum5(12) & NOT a1sum5(12) & NOT a1sum5(12) & NOT a1sum5(12) & NOT a1sum5(12) & NOT a1sum5(12) & NOT a1sum5(12) & NOT a1sum5(12))), 12), 24);

  delay_process_section5 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section5 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section5(1) <= delay_section5(0);
        delay_section5(0) <= typeconvert5;
      END IF;
    END IF;
  END PROCESS delay_process_section5;

  inputconv5 <= section_result4;

  a2mul5 <= delay_section5(0) * coeff_a2_section5;

  a3mul5 <= delay_section5(1) * coeff_a3_section5;

  b2mul5 <= delay_section5(0) * coeff_b2_section5;

  b3mul5 <= delay_section5(1) * coeff_b3_section5;

  sub_cast_16 <= inputconv5;
  sub_cast_17 <= resize(shift_right(a2mul5(47) & a2mul5(47 DOWNTO 0) + ( "0" & (a2mul5(10) & NOT a2mul5(10) & NOT a2mul5(10) & NOT a2mul5(10) & NOT a2mul5(10) & NOT a2mul5(10) & NOT a2mul5(10) & NOT a2mul5(10) & NOT a2mul5(10) & NOT a2mul5(10))), 10), 40);
  sub_temp_8 <= resize(sub_cast_16, 41) - resize(sub_cast_17, 41);
  a2sum5 <= sub_temp_8(39 DOWNTO 0);

  sub_cast_18 <= a2sum5;
  sub_cast_19 <= resize(shift_right(a3mul5(47) & a3mul5(47 DOWNTO 0) + ( "0" & (a3mul5(10) & NOT a3mul5(10) & NOT a3mul5(10) & NOT a3mul5(10) & NOT a3mul5(10) & NOT a3mul5(10) & NOT a3mul5(10) & NOT a3mul5(10) & NOT a3mul5(10) & NOT a3mul5(10))), 10), 40);
  sub_temp_9 <= resize(sub_cast_18, 41) - resize(sub_cast_19, 41);
  a1sum5 <= sub_temp_9(39 DOWNTO 0);

  b1multypeconvert5 <= resize(typeconvert5(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_16 <= b1multypeconvert5;
  add_cast_17 <= resize(shift_right(b2mul5(47) & b2mul5(47 DOWNTO 0) + ( "0" & (b2mul5(10) & NOT b2mul5(10) & NOT b2mul5(10) & NOT b2mul5(10) & NOT b2mul5(10) & NOT b2mul5(10) & NOT b2mul5(10) & NOT b2mul5(10) & NOT b2mul5(10) & NOT b2mul5(10))), 10), 40);
  add_temp_8 <= resize(add_cast_16, 41) + resize(add_cast_17, 41);
  b2sum5 <= add_temp_8(39 DOWNTO 0);

  add_cast_18 <= b2sum5;
  add_cast_19 <= resize(shift_right(b3mul5(47) & b3mul5(47 DOWNTO 0) + ( "0" & (b3mul5(10) & NOT b3mul5(10) & NOT b3mul5(10) & NOT b3mul5(10) & NOT b3mul5(10) & NOT b3mul5(10) & NOT b3mul5(10) & NOT b3mul5(10) & NOT b3mul5(10) & NOT b3mul5(10))), 10), 40);
  add_temp_9 <= resize(add_cast_18, 41) + resize(add_cast_19, 41);
  b1sum5 <= add_temp_9(39 DOWNTO 0);

  section_result5 <= resize(b1sum5(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 6 ------------------

  typeconvert6 <= resize(shift_right(a1sum6(35 DOWNTO 0) + ( "0" & (a1sum6(12) & NOT a1sum6(12) & NOT a1sum6(12) & NOT a1sum6(12) & NOT a1sum6(12) & NOT a1sum6(12) & NOT a1sum6(12) & NOT a1sum6(12) & NOT a1sum6(12) & NOT a1sum6(12) & NOT a1sum6(12) & NOT a1sum6(12))), 12), 24);

  delay_process_section6 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section6 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section6(1) <= delay_section6(0);
        delay_section6(0) <= typeconvert6;
      END IF;
    END IF;
  END PROCESS delay_process_section6;

  inputconv6 <= section_result5;

  a2mul6 <= delay_section6(0) * coeff_a2_section6;

  a3mul6 <= delay_section6(1) * coeff_a3_section6;

  b2mul6 <= delay_section6(0) * coeff_b2_section6;

  b3mul6 <= delay_section6(1) * coeff_b3_section6;

  sub_cast_20 <= inputconv6;
  sub_cast_21 <= resize(shift_right(a2mul6(47) & a2mul6(47 DOWNTO 0) + ( "0" & (a2mul6(10) & NOT a2mul6(10) & NOT a2mul6(10) & NOT a2mul6(10) & NOT a2mul6(10) & NOT a2mul6(10) & NOT a2mul6(10) & NOT a2mul6(10) & NOT a2mul6(10) & NOT a2mul6(10))), 10), 40);
  sub_temp_10 <= resize(sub_cast_20, 41) - resize(sub_cast_21, 41);
  a2sum6 <= sub_temp_10(39 DOWNTO 0);

  sub_cast_22 <= a2sum6;
  sub_cast_23 <= resize(shift_right(a3mul6(47) & a3mul6(47 DOWNTO 0) + ( "0" & (a3mul6(10) & NOT a3mul6(10) & NOT a3mul6(10) & NOT a3mul6(10) & NOT a3mul6(10) & NOT a3mul6(10) & NOT a3mul6(10) & NOT a3mul6(10) & NOT a3mul6(10) & NOT a3mul6(10))), 10), 40);
  sub_temp_11 <= resize(sub_cast_22, 41) - resize(sub_cast_23, 41);
  a1sum6 <= sub_temp_11(39 DOWNTO 0);

  b1multypeconvert6 <= resize(typeconvert6(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_20 <= b1multypeconvert6;
  add_cast_21 <= resize(shift_right(b2mul6(47) & b2mul6(47 DOWNTO 0) + ( "0" & (b2mul6(10) & NOT b2mul6(10) & NOT b2mul6(10) & NOT b2mul6(10) & NOT b2mul6(10) & NOT b2mul6(10) & NOT b2mul6(10) & NOT b2mul6(10) & NOT b2mul6(10) & NOT b2mul6(10))), 10), 40);
  add_temp_10 <= resize(add_cast_20, 41) + resize(add_cast_21, 41);
  b2sum6 <= add_temp_10(39 DOWNTO 0);

  add_cast_22 <= b2sum6;
  add_cast_23 <= resize(shift_right(b3mul6(47) & b3mul6(47 DOWNTO 0) + ( "0" & (b3mul6(10) & NOT b3mul6(10) & NOT b3mul6(10) & NOT b3mul6(10) & NOT b3mul6(10) & NOT b3mul6(10) & NOT b3mul6(10) & NOT b3mul6(10) & NOT b3mul6(10) & NOT b3mul6(10))), 10), 40);
  add_temp_11 <= resize(add_cast_22, 41) + resize(add_cast_23, 41);
  b1sum6 <= add_temp_11(39 DOWNTO 0);

  section_result6 <= resize(b1sum6(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 7 ------------------

  typeconvert7 <= resize(shift_right(a1sum7(35 DOWNTO 0) + ( "0" & (a1sum7(12) & NOT a1sum7(12) & NOT a1sum7(12) & NOT a1sum7(12) & NOT a1sum7(12) & NOT a1sum7(12) & NOT a1sum7(12) & NOT a1sum7(12) & NOT a1sum7(12) & NOT a1sum7(12) & NOT a1sum7(12) & NOT a1sum7(12))), 12), 24);

  delay_process_section7 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section7 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section7(1) <= delay_section7(0);
        delay_section7(0) <= typeconvert7;
      END IF;
    END IF;
  END PROCESS delay_process_section7;

  inputconv7 <= section_result6;

  b2mul7 <= delay_section7(0) * coeff_b2_section7;

  b3mul7 <= delay_section7(1) * coeff_b3_section7;

  a1sum7 <= inputconv7;

  b1multypeconvert7 <= resize(typeconvert7(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_24 <= b1multypeconvert7;
  add_cast_25 <= resize(shift_right(b2mul7(47) & b2mul7(47 DOWNTO 0) + ( "0" & (b2mul7(10) & NOT b2mul7(10) & NOT b2mul7(10) & NOT b2mul7(10) & NOT b2mul7(10) & NOT b2mul7(10) & NOT b2mul7(10) & NOT b2mul7(10) & NOT b2mul7(10) & NOT b2mul7(10))), 10), 40);
  add_temp_12 <= resize(add_cast_24, 41) + resize(add_cast_25, 41);
  b2sum7 <= add_temp_12(39 DOWNTO 0);

  add_cast_26 <= b2sum7;
  add_cast_27 <= resize(shift_right(b3mul7(47) & b3mul7(47 DOWNTO 0) + ( "0" & (b3mul7(10) & NOT b3mul7(10) & NOT b3mul7(10) & NOT b3mul7(10) & NOT b3mul7(10) & NOT b3mul7(10) & NOT b3mul7(10) & NOT b3mul7(10) & NOT b3mul7(10) & NOT b3mul7(10))), 10), 40);
  add_temp_13 <= resize(add_cast_26, 41) + resize(add_cast_27, 41);
  b1sum7 <= add_temp_13(39 DOWNTO 0);

  section_result7 <= resize(b1sum7(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 8 ------------------

  typeconvert8 <= resize(shift_right(a1sum8(35 DOWNTO 0) + ( "0" & (a1sum8(12) & NOT a1sum8(12) & NOT a1sum8(12) & NOT a1sum8(12) & NOT a1sum8(12) & NOT a1sum8(12) & NOT a1sum8(12) & NOT a1sum8(12) & NOT a1sum8(12) & NOT a1sum8(12) & NOT a1sum8(12) & NOT a1sum8(12))), 12), 24);

  delay_process_section8 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section8 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section8(1) <= delay_section8(0);
        delay_section8(0) <= typeconvert8;
      END IF;
    END IF;
  END PROCESS delay_process_section8;

  inputconv8 <= section_result7;

  b2mul8 <= delay_section8(0) * coeff_b2_section8;

  b3mul8 <= delay_section8(1) * coeff_b3_section8;

  a1sum8 <= inputconv8;

  b1multypeconvert8 <= resize(typeconvert8(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_28 <= b1multypeconvert8;
  add_cast_29 <= resize(shift_right(b2mul8(47) & b2mul8(47 DOWNTO 0) + ( "0" & (b2mul8(10) & NOT b2mul8(10) & NOT b2mul8(10) & NOT b2mul8(10) & NOT b2mul8(10) & NOT b2mul8(10) & NOT b2mul8(10) & NOT b2mul8(10) & NOT b2mul8(10) & NOT b2mul8(10))), 10), 40);
  add_temp_14 <= resize(add_cast_28, 41) + resize(add_cast_29, 41);
  b2sum8 <= add_temp_14(39 DOWNTO 0);

  add_cast_30 <= b2sum8;
  add_cast_31 <= resize(shift_right(b3mul8(47) & b3mul8(47 DOWNTO 0) + ( "0" & (b3mul8(10) & NOT b3mul8(10) & NOT b3mul8(10) & NOT b3mul8(10) & NOT b3mul8(10) & NOT b3mul8(10) & NOT b3mul8(10) & NOT b3mul8(10) & NOT b3mul8(10) & NOT b3mul8(10))), 10), 40);
  add_temp_15 <= resize(add_cast_30, 41) + resize(add_cast_31, 41);
  b1sum8 <= add_temp_15(39 DOWNTO 0);

  section_result8 <= resize(b1sum8(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 9 ------------------

  typeconvert9 <= resize(shift_right(a1sum9(35 DOWNTO 0) + ( "0" & (a1sum9(12) & NOT a1sum9(12) & NOT a1sum9(12) & NOT a1sum9(12) & NOT a1sum9(12) & NOT a1sum9(12) & NOT a1sum9(12) & NOT a1sum9(12) & NOT a1sum9(12) & NOT a1sum9(12) & NOT a1sum9(12) & NOT a1sum9(12))), 12), 24);

  delay_process_section9 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section9 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section9(1) <= delay_section9(0);
        delay_section9(0) <= typeconvert9;
      END IF;
    END IF;
  END PROCESS delay_process_section9;

  inputconv9 <= section_result8;

  b2mul9 <= delay_section9(0) * coeff_b2_section9;

  b3mul9 <= delay_section9(1) * coeff_b3_section9;

  a1sum9 <= inputconv9;

  b1multypeconvert9 <= resize(typeconvert9(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_32 <= b1multypeconvert9;
  add_cast_33 <= resize(shift_right(b2mul9(47) & b2mul9(47 DOWNTO 0) + ( "0" & (b2mul9(10) & NOT b2mul9(10) & NOT b2mul9(10) & NOT b2mul9(10) & NOT b2mul9(10) & NOT b2mul9(10) & NOT b2mul9(10) & NOT b2mul9(10) & NOT b2mul9(10) & NOT b2mul9(10))), 10), 40);
  add_temp_16 <= resize(add_cast_32, 41) + resize(add_cast_33, 41);
  b2sum9 <= add_temp_16(39 DOWNTO 0);

  add_cast_34 <= b2sum9;
  add_cast_35 <= resize(shift_right(b3mul9(47) & b3mul9(47 DOWNTO 0) + ( "0" & (b3mul9(10) & NOT b3mul9(10) & NOT b3mul9(10) & NOT b3mul9(10) & NOT b3mul9(10) & NOT b3mul9(10) & NOT b3mul9(10) & NOT b3mul9(10) & NOT b3mul9(10) & NOT b3mul9(10))), 10), 40);
  add_temp_17 <= resize(add_cast_34, 41) + resize(add_cast_35, 41);
  b1sum9 <= add_temp_17(39 DOWNTO 0);

  section_result9 <= resize(b1sum9(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 10 ------------------

  typeconvert10 <= resize(shift_right(a1sum10(35 DOWNTO 0) + ( "0" & (a1sum10(12) & NOT a1sum10(12) & NOT a1sum10(12) & NOT a1sum10(12) & NOT a1sum10(12) & NOT a1sum10(12) & NOT a1sum10(12) & NOT a1sum10(12) & NOT a1sum10(12) & NOT a1sum10(12) & NOT a1sum10(12) & NOT a1sum10(12))), 12), 24);

  delay_process_section10 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section10 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section10(1) <= delay_section10(0);
        delay_section10(0) <= typeconvert10;
      END IF;
    END IF;
  END PROCESS delay_process_section10;

  inputconv10 <= section_result9;

  b2mul10 <= delay_section10(0) * coeff_b2_section10;

  b3mul10 <= delay_section10(1) * coeff_b3_section10;

  a1sum10 <= inputconv10;

  b1multypeconvert10 <= resize(typeconvert10(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_36 <= b1multypeconvert10;
  add_cast_37 <= resize(shift_right(b2mul10(47) & b2mul10(47 DOWNTO 0) + ( "0" & (b2mul10(10) & NOT b2mul10(10) & NOT b2mul10(10) & NOT b2mul10(10) & NOT b2mul10(10) & NOT b2mul10(10) & NOT b2mul10(10) & NOT b2mul10(10) & NOT b2mul10(10) & NOT b2mul10(10))), 10), 40);
  add_temp_18 <= resize(add_cast_36, 41) + resize(add_cast_37, 41);
  b2sum10 <= add_temp_18(39 DOWNTO 0);

  add_cast_38 <= b2sum10;
  add_cast_39 <= resize(shift_right(b3mul10(47) & b3mul10(47 DOWNTO 0) + ( "0" & (b3mul10(10) & NOT b3mul10(10) & NOT b3mul10(10) & NOT b3mul10(10) & NOT b3mul10(10) & NOT b3mul10(10) & NOT b3mul10(10) & NOT b3mul10(10) & NOT b3mul10(10) & NOT b3mul10(10))), 10), 40);
  add_temp_19 <= resize(add_cast_38, 41) + resize(add_cast_39, 41);
  b1sum10 <= add_temp_19(39 DOWNTO 0);

  section_result10 <= resize(b1sum10(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 11 ------------------

  typeconvert11 <= resize(shift_right(a1sum11(35 DOWNTO 0) + ( "0" & (a1sum11(12) & NOT a1sum11(12) & NOT a1sum11(12) & NOT a1sum11(12) & NOT a1sum11(12) & NOT a1sum11(12) & NOT a1sum11(12) & NOT a1sum11(12) & NOT a1sum11(12) & NOT a1sum11(12) & NOT a1sum11(12) & NOT a1sum11(12))), 12), 24);

  delay_process_section11 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section11 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section11(1) <= delay_section11(0);
        delay_section11(0) <= typeconvert11;
      END IF;
    END IF;
  END PROCESS delay_process_section11;

  inputconv11 <= section_result10;

  b2mul11 <= delay_section11(0) * coeff_b2_section11;

  b3mul11 <= delay_section11(1) * coeff_b3_section11;

  a1sum11 <= inputconv11;

  b1multypeconvert11 <= resize(typeconvert11(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_40 <= b1multypeconvert11;
  add_cast_41 <= resize(shift_right(b2mul11(47) & b2mul11(47 DOWNTO 0) + ( "0" & (b2mul11(10) & NOT b2mul11(10) & NOT b2mul11(10) & NOT b2mul11(10) & NOT b2mul11(10) & NOT b2mul11(10) & NOT b2mul11(10) & NOT b2mul11(10) & NOT b2mul11(10) & NOT b2mul11(10))), 10), 40);
  add_temp_20 <= resize(add_cast_40, 41) + resize(add_cast_41, 41);
  b2sum11 <= add_temp_20(39 DOWNTO 0);

  add_cast_42 <= b2sum11;
  add_cast_43 <= resize(shift_right(b3mul11(47) & b3mul11(47 DOWNTO 0) + ( "0" & (b3mul11(10) & NOT b3mul11(10) & NOT b3mul11(10) & NOT b3mul11(10) & NOT b3mul11(10) & NOT b3mul11(10) & NOT b3mul11(10) & NOT b3mul11(10) & NOT b3mul11(10) & NOT b3mul11(10))), 10), 40);
  add_temp_21 <= resize(add_cast_42, 41) + resize(add_cast_43, 41);
  b1sum11 <= add_temp_21(39 DOWNTO 0);

  section_result11 <= resize(b1sum11(38 DOWNTO 0) & '0', 40);

  --   ------------------ Section 12 ------------------

  typeconvert12 <= resize(shift_right(a1sum12(35 DOWNTO 0) + ( "0" & (a1sum12(12) & NOT a1sum12(12) & NOT a1sum12(12) & NOT a1sum12(12) & NOT a1sum12(12) & NOT a1sum12(12) & NOT a1sum12(12) & NOT a1sum12(12) & NOT a1sum12(12) & NOT a1sum12(12) & NOT a1sum12(12) & NOT a1sum12(12))), 12), 24);

  delay_process_section12 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section12 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_section12(1) <= delay_section12(0);
        delay_section12(0) <= typeconvert12;
      END IF;
    END IF;
  END PROCESS delay_process_section12;

  inputconv12 <= section_result11;

  b2mul12 <= delay_section12(0) * coeff_b2_section12;

  b3mul12 <= delay_section12(1) * coeff_b3_section12;

  a1sum12 <= inputconv12;

  b1multypeconvert12 <= resize(typeconvert12(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  add_cast_44 <= b1multypeconvert12;
  add_cast_45 <= resize(shift_right(b2mul12(47) & b2mul12(47 DOWNTO 0) + ( "0" & (b2mul12(10) & NOT b2mul12(10) & NOT b2mul12(10) & NOT b2mul12(10) & NOT b2mul12(10) & NOT b2mul12(10) & NOT b2mul12(10) & NOT b2mul12(10) & NOT b2mul12(10) & NOT b2mul12(10))), 10), 40);
  add_temp_22 <= resize(add_cast_44, 41) + resize(add_cast_45, 41);
  b2sum12 <= add_temp_22(39 DOWNTO 0);

  add_cast_46 <= b2sum12;
  add_cast_47 <= resize(shift_right(b3mul12(47) & b3mul12(47 DOWNTO 0) + ( "0" & (b3mul12(10) & NOT b3mul12(10) & NOT b3mul12(10) & NOT b3mul12(10) & NOT b3mul12(10) & NOT b3mul12(10) & NOT b3mul12(10) & NOT b3mul12(10) & NOT b3mul12(10) & NOT b3mul12(10))), 10), 40);
  add_temp_23 <= resize(add_cast_46, 41) + resize(add_cast_47, 41);
  b1sum12 <= add_temp_23(39 DOWNTO 0);

  output_typeconvert <= resize(shift_right(b1sum12(39 DOWNTO 0) + ( "0" & (b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16) & NOT b1sum12(16))), 16), 24);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= output_register;
END rtl;
